### ISSUE TITLE
c# samples

### ISSUE THREAD

**Issue by mitchcapper** [Microsoft/TVHelpers#11]
It seems this is primarily javascript related (the c# project is just a webview), the description makes it sound like it will include xaml samples?  Is this on the roadmap or is it just a misunderstanding?

**Comment by robcamer** [comment]
Hi and thanks for the feedback.  TVJS provides supplemental functionality to help JavaScript developers build TV apps for UWP.  Otherwise, the functionality provided by TVJS for JavaScript is built into the UWP platform for C# developers.  However, we are nearing release of an end-to-end Media App sample that demonstrates responsive design and development.  Also, additional samples specific to tailoring for TV in XAML/C# will also be released this coming week.

**Comment by dmitryfd** [comment]
Hey @robcamer, 
Any update on the C# samples?

**Comment by apesant** [comment]
Hi @robcamer , any news about the end-to-end media app?

**Comment by robcamer** [comment]
Hi All, apologies for the delay.  Had a customer project that completed and I am back on this.  One issue  left to debug (app fails to launch on clean Windows November Update machine) and then will publish to the GitHub.

**Comment by robcamer** [comment]
Hi Everyone, thank you for your patience.  I published an initial release of the Media App sample.  Xbox One support is not complete as the platform has not shipped and the public preview SDK was not feature complete.  Expect a refresh as we get closer to launch.  Any issues that you find please file in the repo. Thanks!

**Comment by davidezordan** [comment]
Thank you, @robcamer. Great stuff!
