### ISSUE TITLE
Not seeing controls of the MediaPlayer

### ISSUE THREAD

**Issue by jackhand** [Microsoft/TVHelpers#22]
I am not seeing the controls for the MediaPlayer. Is there a trick in showing the buttons after instantiation? 

var mediaPlayer = new TVJS.MediaPlayer(document.getElementById("myControls"));

**Comment by payzer** [comment]
There's no trick. That should just work. Did you try the basic sample?

We may have some browser compat issues at the moment. Try the basic sample in Edge & let me know if that is not working.

**Comment by jackhand** [comment]
I'm using it within a Universal app.

**Comment by payzer** [comment]
Okay. Let me try the basic sample in a universal app to see if I can repro.

**Comment by payzer** [comment]
I had a chat with Rob who is working on a sample so he'll have an update for you when he's ready :)

**Comment by robcamer** [comment]
I built a quick sample between meetings :-) and found that I had to mark the font in the properties window in VS as “content” so that it was included with the rest of the web files.  That resolved the buttons having icons in the WebView for me.

I posted a sample here:
https://1drv.ms/f/s!As9wzthmMrK4rOUvv1GI5s4UvKYk7Q

Hope this helps!

Thanks,
-Rob

**Comment by jackhand** [comment]
In order for me to see the controls I had to set the video tag's z-index to 0. (I noticed that the CSS has it originally set to "1".)

**Comment by robcamer** [comment]
Not sure why that’s the case in your case, I did not need to do that for the sample but glad to hear it was resolved.  Thanks for letting us know!

**Comment by payzer** [comment]
Closing. Sound like this is resolved.
