### ISSUE TITLE
Focus management thinking around WinJS controls? (Pivot)

### ISSUE THREAD

**Issue by staxmanade** [Microsoft/TVHelpers#31]
I haven't tested other controls, but researching issues around the WinJS Pivot control, I'm seeing what appears to be a pretty big disconnect between the `DirectionalNavigation` and the WinJS Pivot control.

Are there any guidelines or thoughts on how to make the two play nice together? Or any other WinJS controls for that matter?

Specifically, the Pivot control handles it's own focus management (selecting tabs) - but the `DirectionalNavigation` doesn't allow the tab focusing to happen - causing it to jump off of the Pivot control to other elements on the page.

I'm looking into the `TVJS.DirectionalNavigation.enabled = false` workflow at the moment, but am hoping there's already been some thinking around this and I don't have to re-invent the focus wheel.

Thoughts?

**Comment by payzer** [comment]
The recommended pattern for using Directional Navigation with other controls that manage focus themselves is to:
1. Detect when focus is inside a control that manages focus itself and set TVJS.DirectionalNavigation.enabled = false.
2. (this part often requires modifying the library code that has the control) If the control does not find a focusable element using it's internal logic, then call TVJS.DirectionalNavigation.moveFocus, passing the direction (usually the control has a variable that tracks this) and options,referenceRect, which you can usually use document.activeElement.getBoundingClientRect() for.

Since you are using WinJS, the controls you may need to modify would be the Pivot, Hub, Menu and ListView.

This issue topic has code for modifying the ListView:

https://github.com/Microsoft/TVHelpers/issues/18

**Comment by staxmanade** [comment]
For any poor sap who's doing this like myself... I have a [blog post](http://staxmanade.com/2016/12/tvjs-tvhelpers-directionalnavigation-and-adapting-hacking-some-winjs-focus-management/) with a list of my work-arounds and hacks that have worked for me. I'll continue to evolve it as I find better ways, but may the force be with those of us poor saps still trying to use WinJS.
