### ISSUE TITLE
DirectionalNavigation does intercept first keyPress on input fields

### ISSUE THREAD

**Issue by vgrafe** [Microsoft/TVHelpers#42]
in my hosted XBOX UWP javascript webapp, I found that `<input type='text' />` fields would not bring the virtual keyboard on the first press to the A button. The second press brings it.

I figured that after calling 
```
window.navigator.gamepadInputEmulation = "gamepad";
```
on the `onfocus` event on the fields, the first keyDown with A shows the keyboard, but once the text is typed, I can't navigate away using the controller. A workaround would be to set the property back to "keyboard", but I could not find a way to detect when the keyboard is being hidden in javascript.

Is there any way to workaround that bug? Thanks!

**Comment by payzer** [comment]
The way most people do it is using the hiding / showing events on the InputPane class:
https://docs.microsoft.com/en-us/uwp/api/Windows.UI.ViewManagement.InputPane

The keyboard is usually dismissed with B since it's modal, but if you want to programmatically show & hide it, you can use the InputPane APIs to do that.
